### ISSUE TITLE
Nice project! Some benchmarks/larger examples?

### ISSUE THREAD

**Issue by wizzard0** [GJDuck/libf#1]
well, it's all in the title :)

**Comment by GJDuck** [comment]
Unfortunately --- not yet.  But I am hoping to find some spare time to revisit this project soon(ish).  The main todo list is:

* Revamp to use more C++ features.  Originally I envisaged this as a C extension, but in hindsight made some things needlessly difficult.  I think this project makes more sense as a functional C++ subset.
* Implement iterators.  Iterators are "stateful", so not really "pure", but are more flexible than trying to squeeze everything into `foldl`.  This also allows for C++ range based loops which are "pure".

**Comment by GJDuck** [comment]
A new version is available which fixes all the above mentioned issues.  Some benchmarks and other examples are also provided.
