### ISSUE TITLE
Use of 2-3 Finger Trees

### ISSUE THREAD

**Issue by d-s-d** [GJDuck/libf#3]
Hi.

I couldn't find any forum, discussion group or eMail-Address, hence I allowed myself to ask this question here.

While looking for an implementation of finger trees in C++, I came across libf. Using the implementation of 23-fingertrees underlying the sequence type, is it possible to annotate each node with a measure?

More concretely, what I'm trying to do is very similar to this: http://jkff.info/articles/ire/

many thanks.

**Comment by GJDuck** [comment]
> Using the implementation of 23-fingertrees underlying the sequence type, is it possible to annotate each node with a measure?

Yes, probably.  There is already a `len` field for every node that can be generalized to other types/operations beyond `size_t` and `+`.  This was on the TODO list but never implemented since ultimately there was no need (for `F::String` and `F::Vector` at least).
